
service: ToDoList

provider:
  name: aws
  runtime: nodejs8.10
  region: us-west-1
  environment:
    TASKS_TABLE: ${self:custom.tableName}
    AWS_DEPLOY_REGION: ${self:provider.region}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["TaskTable", "Arn" ] }

functions:
  createTask:
    handler: handler.createTask
    events:
      - http:
          path: /tasks/create
          method: post
          cors: true
  getAllTasks:
    handler: handler.getAllTasks
    events:
      - http:
          path: /tasks/all
          method: get
          cors: true
  getTasksByStatus:
    handler: handler.getTasksByStatus
    events:
      - http:
          path: /tasks/filter
          method: get
          request:
            template:
              application/json: >
                {
                  "status":"$input.params('status')"
                }
  updateTask:
    handler: handler.updateTask
    events:
      - http:
          path: /tasks/update/{taskId}
          method: patch
          cors: true
  deleteTask:
    handler: handler.deleteTask
    events:
      - http:
          path: /tasks/delete/{taskId}
          method: delete
          cors: true

custom: 
  # Selects stage, else falls back onto self's provider stage.
  stage: ${opt:stage, self:provider.stage}
  tableName: ${self:custom.stage}-Task
  # Setting DynamoDB throughput for prod and default for all other non-prod stages.
  tableThroughputs:
    prod: 5
    default: 1
  tableThroughput: ${self:custom.tableThroughputs.${self:custom.stage}, self:custom.tableThroughputs.default}


# Create our resources with separate templates
resources:
  # DynamoDB
  - ${file(resources/dynamodb-table.yml)}

